-- A coluna que faz o fluxo deixar de ser uma fila e virar um mapa de caminhos.
--
-- POR QUE ELA PRECISA EXISTIR ANTES DO CÓDIGO NOVO SUBIR:
-- o motor da Fase 2a caminha seguindo as setas gravadas aqui. Com a coluna
-- ausente ou vazia, a caminhada para no bloco de entrada e ninguém recebe nada
-- — e não estoura, porque `lib/engine.ts` usa `select *`, a coluna faltando
-- vira `undefined` e `ligacoesDe` devolve `[]`. Medido: uma automação de cinco
-- blocos passa a entregar um. Silêncio total.
--
-- Por isso a ordem é: esta migração, depois `scripts/ligar-passos-existentes.mjs`
-- (que preenche a corrente), e só então o deploy.
--
-- IDEMPOTENTE por construção (`if not exists`), que é o contrato de toda
-- migração desta pasta enquanto não houver tabela de controle. Ver o cabeçalho
-- de `scripts/migrar.mjs`.
--
-- Acrescentar coluna com `default` não reescreve a tabela no Postgres 11+,
-- então roda rápido mesmo com dados.
--
-- ESTA LINHA JÁ ESTEVE EM DOIS LUGARES, e desde 26/08 está só aqui. Durante a
-- transição ela também vivia em `lib/db.ts` (`ensureSchema`): lá era a REDE (se
-- alguém implantasse sem rodar isto, a coluna ainda nascia), aqui é a ORDEM
-- (existir antes do código subir). **A rede foi apagada.** Não há mais nada na
-- aplicação criando esta coluna, e um banco que não rodar esta migração faz o
-- motor ler `undefined` de `select *` e decidir diferente sem erro nenhum —
-- medido, e é a razão de `exigirEsquema()` (lib/esquema.ts) existir.
alter table automations
  add column if not exists ligacoes jsonb not null default '[]'::jsonb;
